services:
- type: web
  runtime: python
  name: kodaworld-backend
  dockerfilePath: Dockerfile
  autoDeploy: true
  plan: free
  envVars:
  - key: DATABASE_URL
    value: <Your Postgres database URL>
  - key: REDIS_URL
    value: <Your Redis URL>
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn ai71.main:app --host 0.0.0.0 --port 8000
