"""Initial migration

Revision ID: d012c4d46f62
Revises: 
Create Date: 2024-08-07 06:12:20.792876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd012c4d46f62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculums', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('curriculums', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('learning_goals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'learning_goals', 'users', ['user_id'], ['id'])
    op.add_column('performance_data', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('performance_data', sa.Column('chapter', sa.Text(), nullable=False))
    op.add_column('performance_data', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'performance_data', 'users', ['user_id'], ['id'])
    op.drop_column('performance_data', 'specific')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_data', sa.Column('specific', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'performance_data', type_='foreignkey')
    op.drop_column('performance_data', 'timestamp')
    op.drop_column('performance_data', 'chapter')
    op.drop_column('performance_data', 'user_id')
    op.drop_constraint(None, 'learning_goals', type_='foreignkey')
    op.drop_column('learning_goals', 'user_id')
    op.drop_column('curriculums', 'updated_at')
    op.drop_column('curriculums', 'created_at')
    # ### end Alembic commands ###
